apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    volume: db-pv
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  nfs:
    server: 161.35.63.181
    path: /share

