apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-14T21:38:45Z"
  labels:
    app: wordpress
  name: lbw
  namespace: default
  resourceVersion: "3780195"
  selfLink: /api/v1/namespaces/default/services/lbw
  uid: 6ce1f8b0-ae87-11ea-baef-42010a8001f0
spec:
  clusterIP: 10.0.7.197
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30357
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.69.89.55
